name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: |
          cd RAnlab-master
          composer install --no-dev --optimize-autoloader

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies and build assets
        run: |
          cd RAnlab-master
          npm install
          npm run production  # Adjust the script as needed

      - name: Set up MySQL
        uses: crazy-max/ghaction-mysql@v1
        with:
          mysql-version: '8.0'
          db: ranlab  # Change the database name as needed

      - name: Run database migrations
        run: |
          cd RAnlab-master
          php artisan migrate --force

      - name: Seed database
        run: |
          cd RAnlab-master
          php artisan db:seed --force

      - name: Start Laravel server
        run: |
          cd RAnlab-master
          php artisan serve --port ${{ env.PORT }} --host 0.0.0.0 &

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/ghaction-pages@main
        with:
          site-id: ${{ secrets.CLOUDFLARE_PAGES_SITE_ID }}
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
